name = "cctv-api"
main = "worker.js"
compatibility_date = "2024-04-05"

# Konfigurasi Database D1 (Hasil Konversi dari JSON Anda)
[[d1_databases]]
binding = "DB" # Ini nama variabel yang akan dipanggil di worker.js
database_name = "produku"
database_id = "234a1f83-efeb-43ce-84d2-086f32b85688"